### ISSUE TITLE
Cannot find package "." in

### ISSUE THREAD

**Issue by JonathanLorimer** [nix-community/gomod2nix#20] opened 2021-09-08 14:26 UTC
**Describe the bug**
gomod2nix seems to struggle with go dependencies that are part of the repo and referenced by relative paths. When I try and package [regen-network](https://github.com/regen-network/regen-ledger) I am getting this error:
```
app/app.go:10:2: cannot find package "." in:
        /build/source/vendor/github.com/regen-network/regen-ledger/types/module
app/app.go:95:2: cannot find package "." in:
        /build/source/vendor/github.com/regen-network/regen-ledger/types/module/server
app/app.go:96:2: cannot find package "." in:
        /build/source/vendor/github.com/regen-network/regen-ledger/x/ecocredit
app/app.go:11:2: cannot find package "." in:
        /build/source/vendor/github.com/regen-network/regen-ledger/x/ecocredit/module
```

The issue seems to be with these [dependencies](https://github.com/regen-network/regen-ledger/blob/master/go.mod#L30-L38). The relevant error sites are listed below:
- https://github.com/regen-network/regen-ledger/blob/master/app/app.go#L10-L11
- https://github.com/regen-network/regen-ledger/blob/master/app/app.go#L95-L96

I also think that this has something to do with the local replace directives [here](https://github.com/regen-network/regen-ledger/blob/master/go.mod#L30-L38)
**To Reproduce**
I created a repro repo [here](https://github.com/JonathanLorimer/gomod-reprpo-1). You should just have to run `nix build` to get the error. Since the repo is a flake you can just run `nix build github:JonathanLorimer/gomod-repro-1` without even cloning the repo.

**Expected behavior**
I expected this module to build without errors

**Environment**
 - OS name + version: `NixOS 21.11 (Porcupine) x86_64`
 - Version of the code: `67f22dd738d092c6ba88e420350ada0ed4992ae8`

**Additional context**
I have very limited golang knowledge so there might be something completely wrong with the go side of things and I am just missing it. Thank you for your help in advance!

**Comment by JonathanLorimer** [comment] 2021-09-08 16:56
Getting this issue resolved will help me close https://github.com/informalsystems/cosmos.nix/issues/19

**Comment by JonathanLorimer** [comment] 2021-09-25 15:53
Okay, I think I have identified what the issue is! These local, relative path, directives don't end up in the `go.sum`. This means that gomod2nix doesn't end up picking them up and they are missing from the `vendor-env`! I am not sure what the best solution to this is, right now I am trying to figure out a hacky work around to just splice in the dependency I need.

**Comment by 573** [comment] 2022-03-31 17:32
Have similar issue with packaging [dasel](/TomWright/dasel).

**Comment by 573** [comment] 2022-04-26 09:36
Similar issue (`Cannot find package "." in`) when packaging https://github.com/mickael-menu/zk.
The customVendorSrc (#22) there would be https://github.com/aymerick/raymond/.

**Comment by adisbladis** [comment] 2022-05-29 09:10
This issue is not fully resolved but was auto-closed by Github when #41 was merged.

**Comment by thegergo02** [comment] 2022-06-27 10:22
This might be a different issue though? (There are not really local packages...)
```
../protoc-base/templates.go:9:2: cannot find package "." in:
        /build/source/gopath/src/github.com/zitadel/zitadel/vendor/github.com/Masterminds/sprig
../protoc-base/protoc_helper.go:12:2: cannot find package "." in:
        /build/source/gopath/src/github.com/zitadel/zitadel/vendor/github.com/golang/glog
../protoc-base/protoc_helper.go:13:2: cannot find package "." in:
        /build/source/gopath/src/github.com/zitadel/zitadel/vendor/github.com/golang/protobuf/proto
../protoc-base/protoc_helper.go:14:2: cannot find package "." in:
        /build/source/gopath/src/github.com/zitadel/zitadel/vendor/github.com/golang/protobuf/protoc-gen-go/plugin
../protoc-base/protoc_helper.go:15:2: cannot find package "." in:
        /build/source/gopath/src/github.com/zitadel/zitadel/vendor/github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway/descriptor
../protoc-base/templates.go:12:2: cannot find package "." in:
        /build/source/gopath/src/github.com/zitadel/zitadel/vendor/golang.org/x/tools/imports
authoption/options.pb.go:10:2: cannot find package "." in:
        /build/source/gopath/src/github.com/zitadel/zitadel/vendor/google.golang.org/protobuf/reflect/protoreflect
authoption/options.pb.go:11:2: cannot find package "." in:
        /build/source/gopath/src/github.com/zitadel/zitadel/vendor/google.golang.org/protobuf/runtime/protoimpl
authoption/options.pb.go:12:2: cannot find package "." in:
        /build/source/gopath/src/github.com/zitadel/zitadel/vendor/google.golang.org/protobuf/types/descriptorpb
```

**Comment by thegergo02** [comment] 2022-06-27 10:39
Actually, this is still in the configurePhase, as I need to generate some go files there. Irrelevant to this issue then.

**Comment by 0xmuralik** [comment] 2022-10-25 08:51
Any fixes or workarounds for this?

**Comment by skykanin** [comment] 2022-12-14 09:29
I just ran into this same issue. Are there any fixes or workarounds for this?

**Comment by peterldowns** [comment] 2023-02-24 21:14
^ I have the same issue, [here's a minimal repro](https://github.com/peterldowns/gomod2nix-failure-repro). What is the current status of this repository -- is it maintained?

**Comment by ezdac** [comment] 2023-04-04 20:45
@peterldowns  - I hit a very similar issue at the same opentelemetry module.

```
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Building subPackage .
go: finding module for package go.opentelemetry.io/otel/exporters/otlp/internal
vendor/go.opentelemetry.io/otel/exporters/otlp/otlptrace/exporter.go:22:2: cannot query module due to -mod=vendor
```

Internally the buildPhase seems to call `go install -mod=vendor . ` but then tries to query for the module  in the `otel/exporter.go`  imports. Go install does not seem to allow this with the `mod=vendor `([this](https://github.com/golang/go/blob/6d2cac12dbbd0e2f349106f1e4990b2feb0dda40/src/cmd/go/internal/modload/query.go#L127-L132) is the error).

Maybe go install tries to fetch the module because it can't find it in the vendored modules in a similar way that it `cannot find package "." `?

**Comment by peterldowns** [comment] 2023-04-04 21:47
@ezdac hmm, I'm not sure. I was not able to find a fix for this problem and I worked around it by removing opentelemetry as a dependency from my project (it wasn't necessary, thankfully). It doesn't seem like anyone is working on this issue and I myself am not inclined to. You may consider putting up an easy way to reproduce the failure you're receiving, similar to what I did, to help the maintainers out if in the future they decide to try to fix this.

**Comment by JonathanLorimer** [comment] 2023-04-04 21:49
fwiw I just switched to using `buildGoMod119` from nixpkgs, [example here](https://github.com/informalsystems/cosmos.nix/blob/master/resources/utilities.nix#L47-L63). Might be worth it if you have to depend on a package that breaks gomod2nix.

**Comment by niklashhh** [comment] 2023-08-16 19:14
I believe this issue is caused by the weird module structure of `go.opentelemetry.io/otel/exporters`. I changed [`populateVendorPath`](https://github.com/nix-community/gomod2nix/blob/3cbf3a51fe32e2f57af4c52744e7228bab22983d/builder/symlink/symlink.go#L84) to be recursive as hinted by the TODO which fixed the issue in my case. 

Here is some logs indicating that it had to go three directories deep to create the missing symlinks:
```
vendor-env> symlink error, trying /nix/store/93w4h87w5hd0sz90mx8bcbd539v58y56-otel_v1.16.0/exporters symlink /nix/store/93w4h87w5hd0sz90mx8bcbd539v58y56-otel_v1.16.0/exporters vendor/go.opentelemetry.io/otel/exporters: file exists
vendor-env> symlink error, trying /nix/store/93w4h87w5hd0sz90mx8bcbd539v58y56-otel_v1.16.0/exporters/otlp symlink /nix/store/93w4h87w5hd0sz90mx8bcbd539v58y56-otel_v1.16.0/exporters/otlp vendor/go.opentelemetry.io/otel/exporters/otlp: file exists
vendor-env> symlink error, trying /nix/store/93w4h87w5hd0sz90mx8bcbd539v58y56-otel_v1.16.0/exporters/otlp/internal symlink /nix/store/93w4h87w5hd0sz90mx8bcbd539v58y56-otel_v1.16.0/exporters/otlp/internal vendor/go.opentelemetry.io/otel/exporters/otlp/internal: file exists
```

**Closed** 2024-05-30 06:32 UTC
